server:
  port: 9192

spring:
  datasource:
    username: your_username
    password: your_password
    url: jdbc:mysql://localhost:3306/your_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
